import Footer from '@/components/Footer'
import About from '../components/About'
import React from 'react'
import Skills from '@/components/Skills'
import Pdf from '@/components/Pdf'
import Head from 'next/head'

const about = () => {
  return (
    <div>

      <Head>
        <title>Diether De Luna | About Me</title>
        <meta name='description' content='Generated by Created Next App'/>
        <link rel='icon' href='/delicon.png'/>
      </Head>

        <About/>
        <Skills/>
        <Pdf/>
        <Footer/>
    </div>
  )
}

export default about
