import Footer from '@/components/Footer'
import About from '../components/About'
import React from 'react'
import Skills from '@/components/Skills'
import Pdf from '@/components/Pdf'
import Contacts from '@/components/Contacts'
import Head from 'next/head'

const contact = () => {
  return (
    <div>
      <Head>
        <title>Diether De Luna | Contact</title>
        <meta name='description' content='Generated by Created Next App'/>
        <link rel='icon' href='/db.png'/>
      </Head>

        <Contacts/>
        <Footer/>
    </div>
  )
}

export default contact