import Footer from '@/components/Footer'
import About from '../components/About'
import React from 'react'
import Skills from '@/components/Skills'
import Pdf from '@/components/Pdf'
import Contacts from '@/components/Contacts'
import Experience from '@/components/Experience'
import Head from 'next/head'

const experience = () => {
  return (
    <div>
      
      <Head>
        <title>Diether De Luna | Experience</title>
        <meta name='description' content='Generated by Created Next App'/>
        <link rel='icon' href='/dd-icon.png'/>
      </Head>

        <Experience/>
        <Footer/>
    </div>
  )
}

export default experience
